Milk Quality Prediction using Artificial Neural Network (ANN)

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from keras.models import Sequential
from keras.layers import Dense

In [2]:
dataset = pd.read_csv("milknew.csv")

dataset.head()

    pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
0  6.6          35      1     0     1          0     254    high
1  6.6          36      0     1     0          1     253    high
2  8.5          70      1     1     1          1     246     low
3  9.5          34      1     1     0          1     255     low
4  6.6          37      0     0     0          0     255  medium

In [3]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   pH          1059 non-null   float64
 1   Temprature  1059 non-null   int64
 2   Taste       1059 non-null   int64
 3   Odor        1059 non-null   int64
 4   Fat         1059 non-null   int64
 5   Turbidity   1059 non-null   int64
 6   Colour      1059 non-null   int64
 7   Grade       1059 non-null   str
dtypes: float64(1), int64(6), str(1)
memory usage: 70.8 KB

In [4]:
dataset.describe()

,pH,Temprature,Taste,Odor,Fat,Turbidity,Colour
count,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000
mean,6.630123,44.226629,0.546742,0.432483,0.671388,0.491029,251.840415
std,1.399679,10.098364,0.498046,0.495655,0.469930,0.500156,4.307424
min,3.000000,34.000000,0.000000,0.000000,0.000000,0.000000,240.000000
25%,6.500000,38.000000,0.000000,0.000000,0.000000,0.000000,250.000000
50%,6.700000,41.000000,1.000000,0.000000,1.000000,0.000000,255.000000
75%,6.800000,45.000000,1.000000,1.000000,1.000000,1.000000,255.000000
max,9.500000,90.000000,1.000000,1.000000,1.000000,1.000000,255.000000

In [5]:
dataset.isnull().sum()

pH            0
Temprature    0
Taste         0
Odor          0
Fat           0
Turbidity     0
Colour        0
Grade         0
dtype: int64

In [6]:
le = LabelEncoder()

dataset["Grade"] = le.fit_transform(dataset["Grade"])

In [7]:
dataset.head()

    pH  Temprature  Taste  Odor  Fat   Turbidity  Colour  Grade
0  6.6          35      1     0     1          0     254      0
1  6.6          36      0     1     0          1     253      0
2  8.5          70      1     1     1          1     246      1
3  9.5          34      1     1     0          1     255      1
4  6.6          37      0     0     0          0     255      2

In [8]:
X = dataset.drop("Grade", axis=1)

y = dataset["Grade"]

In [9]:
train_X, test_X, train_y, test_y = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=123
)

In [10]:
sc = StandardScaler()

train_X = sc.fit_transform(train_X)

test_X = sc.transform(test_X)

In [12]:
#Build ANN
model = Sequential()
model.add(Dense(units=8,activation="relu",input_dim=7))
model.add(Dense(units=6,activation="relu"))
model.add(Dense(units=4,activation="relu"))
model.add(Dense(units=3,activation="softmax"))

C:\Users\lenovo\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
#compile
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

In [15]:
#train
model.fit(train_X,train_y,epochs=50,batch_size=32,validation_split=0.1)

Epoch 1/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.3874 - loss: 1.0803 - val_accuracy: 0.3867 - val_loss: 1.0350
Epoch 2/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3889 - loss: 0.9943 - val_accuracy: 0.5067 - val_loss: 0.9574
Epoch 3/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4850 - loss: 0.9402 - val_accuracy: 0.5200 - val_loss: 0.9039
Epoch 4/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4700 - loss: 0.8989 - val_accuracy: 0.5333 - val_loss: 0.8572
Epoch 5/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4970 - loss: 0.8608 - val_accuracy: 0.6000 - val_loss: 0.8189
Epoch 6/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5420 - loss: 0.8248 - val_accuracy: 0.6000 - val_loss: 0.7818
Epoch 7/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5766 - loss: 0.7874 - val_accuracy: 0.6667 - val_loss: 0.7463
Epoch 8/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6246 - loss: 0.7541 - val_accuracy: 0.7200 - val_loss: 0.7152
Epoch 9/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.7239 - val_accuracy: 0.7733 - val_loss: 0.6857
Epoch 10/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7943 - loss: 0.6950 - val_accuracy: 0.8267 - val_loss: 0.6573
Epoch 11/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8063 - loss: 0.6666 - val_accuracy: 0.8400 - val_loss: 0.6296
Epoch 12/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8108 - loss: 0.6381 - val_accuracy: 0.8533 - val_loss: 0.6020
Epoch 13/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8213 - loss: 0.6109 - val_accuracy: 0.8533 - val_loss: 0.5769
Epoch 14/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8288 - loss: 0.5852 - val_accuracy: 0.8667 - val_loss: 0.5521
Epoch 15/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8468 - loss: 0.5599 - val_accuracy: 0.9067 - val_loss: 0.5280
Epoch 16/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8634 - loss: 0.5345 - val_accuracy: 0.9067 - val_loss: 0.5039
Epoch 17/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8994 - loss: 0.5100 - val_accuracy: 0.9200 - val_loss: 0.4799
Epoch 18/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9054 - loss: 0.4850 - val_accuracy: 0.9200 - val_loss: 0.4556
Epoch 19/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9159 - loss: 0.4619 - val_accuracy: 0.9333 - val_loss: 0.4321
Epoch 20/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9309 - loss: 0.4397 - val_accuracy: 0.9200 - val_loss: 0.4116
Epoch 21/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9279 - loss: 0.4199 - val_accuracy: 0.9200 - val_loss: 0.3908
Epoch 22/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9249 - loss: 0.4017 - val_accuracy: 0.9333 - val_loss: 0.3720
Epoch 23/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9384 - loss: 0.3844 - val_accuracy: 0.9200 - val_loss: 0.3534
Epoch 24/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9249 - loss: 0.3674 - val_accuracy: 0.9333 - val_loss: 0.3375
Epoch 25/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9309 - loss: 0.3517 - val_accuracy: 0.9467 - val_loss: 0.3196
Epoch 26/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9264 - loss: 0.3369 - val_accuracy: 0.9467 - val_loss: 0.3037
Epoch 27/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9264 - loss: 0.3241 - val_accuracy: 0.9467 - val_loss: 0.2885
Epoch 28/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9414 - loss: 0.3107 - val_accuracy: 0.9333 - val_loss: 0.2758
Epoch 29/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9234 - loss: 0.2997 - val_accuracy: 0.9333 - val_loss: 0.2620
Epoch 30/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9264 - loss: 0.2884 - val_accuracy: 0.9333 - val_loss: 0.2492
Epoch 31/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9234 - loss: 0.2794 - val_accuracy: 0.9333 - val_loss: 0.2375
Epoch 32/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9279 - loss: 0.2693 - val_accuracy: 0.9467 - val_loss: 0.2268
Epoch 33/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9264 - loss: 0.2597 - val_accuracy: 0.9600 - val_loss: 0.2146
Epoch 34/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9324 - loss: 0.2516 - val_accuracy: 0.9600 - val_loss: 0.2055
Epoch 35/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9324 - loss: 0.2449 - val_accuracy: 0.9600 - val_loss: 0.1958
Epoch 36/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9324 - loss: 0.2378 - val_accuracy: 0.9600 - val_loss: 0.1867
Epoch 37/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9324 - loss: 0.2307 - val_accuracy: 0.9600 - val_loss: 0.1769
Epoch 38/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9324 - loss: 0.2241 - val_accuracy: 0.9600 - val_loss: 0.1694
Epoch 39/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9324 - loss: 0.2184 - val_accuracy: 0.9600 - val_loss: 0.1630
Epoch 40/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9324 - loss: 0.2136 - val_accuracy: 0.9600 - val_loss: 0.1570
Epoch 41/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9324 - loss: 0.2090 - val_accuracy: 0.9600 - val_loss: 0.1519
Epoch 42/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9324 - loss: 0.2047 - val_accuracy: 0.9600 - val_loss: 0.1468
Epoch 43/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9324 - loss: 0.2014 - val_accuracy: 0.9600 - val_loss: 0.1414
Epoch 44/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9324 - loss: 0.1977 - val_accuracy: 0.9600 - val_loss: 0.1375
Epoch 45/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9369 - loss: 0.1948 - val_accuracy: 0.9600 - val_loss: 0.1330
Epoch 46/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9324 - loss: 0.1913 - val_accuracy: 0.9600 - val_loss: 0.1306
Epoch 47/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9459 - loss: 0.1886 - val_accuracy: 0.9733 - val_loss: 0.1263
Epoch 48/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9565 - loss: 0.1860 - val_accuracy: 0.9733 - val_loss: 0.1225
Epoch 49/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9489 - loss: 0.1838 - val_accuracy: 0.9733 - val_loss: 0.1210
Epoch 50/50
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9580 - loss: 0.1809 - val_accuracy: 0.9867 - val_loss: 0.1170

In [16]:
model.evaluate(test_X,test_y)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9937 - loss: 0.1212

[0.12121149152517319, 0.9937106966972351]

In [17]:
predictions = model.predict(test_X)

predictions

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

array([[2.2011888e-03, 9.2034012e-02, 9.0576476e-01],
       [1.0568111e-02, 1.1802613e-01, 8.7140578e-01],
       [1.1357708e-04, 9.9936503e-01, 5.2144285e-04],
       [2.3272466e-02, 9.6709329e-01, 9.6341940e-03],
       [6.5579246e-05, 5.1017802e-02, 9.4891661e-01],
       [2.2011888e-03, 9.2034012e-02, 9.0576476e-01],
       [3.2992369e-07, 9.9999964e-01, 6.8688070e-22],
       [1.3456366e-02, 9.3486392e-01, 5.1679734e-02],
       [1.0023474e-02, 8.5710621e-01, 1.3287039e-01],
       [5.2213854e-05, 4.9063981e-02, 9.5088375e-01],
       [1.5646046e-02, 1.2514652e-01, 8.5920745e-01],
       [2.3932655e-04, 6.3594721e-02, 9.3616587e-01],
       [1.5646046e-02, 1.2514652e-01, 8.5920745e-01],
       [4.5447669e-05, 4.7909454e-02, 9.5204514e-01],
       [9.5335782e-01, 4.6641584e-02, 5.3061785e-07],
       [5.2213854e-05, 4.9063981e-02, 9.5088375e-01],
       [3.5946585e-05, 9.9996400e-01, 4.5454566e-15],
       [7.6590438e-04, 9.9923408e-01, 7.2199594e-11],
       [9.7528934e-01, 2.4710635e-02, 1.5274074e-08],
       [7.0184833e-01, 8.8495493e-02, 2.0965612e-01],
       [2.7193356e-01, 2.9226997e-01, 4.3579647e-01],
       [9.3313202e-04, 9.9906689e-01, 4.1811834e-08],
       [5.2213854e-05, 4.9063981e-02, 9.5088375e-01],
       [9.9360472e-01, 6.3952007e-03, 1.7713636e-07],
       [3.5946585e-05, 9.9996400e-01, 4.5454566e-15],
       [7.6590438e-04, 9.9923408e-01, 7.2199594e-11],
       [2.3932655e-04, 6.3594721e-02, 9.3616587e-01],
       [2.7193356e-01, 2.9226997e-01, 4.3579647e-01],
       [2.1784363e-02, 1.3122371e-01, 8.4699190e-01],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [1.0023483e-02, 8.5710621e-01, 1.3287036e-01],
       [2.9017447e-04, 8.2932991e-01, 1.7037991e-01],
       [1.3456366e-02, 9.3486392e-01, 5.1679734e-02],
       [2.3272466e-02, 9.6709329e-01, 9.6341940e-03],
       [1.1357708e-04, 9.9936503e-01, 5.2144285e-04],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [2.3932655e-04, 6.3594721e-02, 9.3616587e-01],
       [2.6049574e-07, 9.9999952e-01, 2.5642558e-07],
       [9.7528934e-01, 2.4710635e-02, 1.5274074e-08],
       [9.9438173e-01, 5.6183534e-03, 4.6722878e-08],
       [3.4961957e-01, 3.1459177e-01, 3.3578873e-01],
       [1.3568453e-04, 5.7757817e-02, 9.4210654e-01],
       [5.2213854e-05, 4.9063981e-02, 9.5088375e-01],
       [9.9234313e-01, 7.6562306e-03, 5.6153419e-07],
       [7.0449010e-02, 1.5088785e-01, 7.7866316e-01],
       [9.9330103e-01, 6.6987542e-03, 2.7103613e-07],
       [8.5504991e-01, 6.9153644e-02, 7.5796537e-02],
       [5.9600687e-01, 3.7871373e-01, 2.5279410e-02],
       [3.8490526e-02, 1.4147425e-01, 8.2003516e-01],
       [3.0326344e-02, 9.6145451e-01, 8.2191294e-03],
       [5.2213854e-05, 4.9063981e-02, 9.5088375e-01],
       [4.4117826e-01, 1.1305902e-01, 4.4576275e-01],
       [5.0756789e-06, 9.9972361e-01, 2.7130864e-04],
       [1.3568453e-04, 5.7757817e-02, 9.4210654e-01],
       [9.9360472e-01, 6.3952007e-03, 1.7713636e-07],
       [8.5504991e-01, 6.9153644e-02, 7.5796537e-02],
       [9.9438173e-01, 5.6183534e-03, 4.6722878e-08],
       [7.0449010e-02, 1.5088785e-01, 7.7866316e-01],
       [3.5702065e-01, 6.2901068e-01, 1.3968632e-02],
       [1.1357708e-04, 9.9936503e-01, 5.2144285e-04],
       [2.2011888e-03, 9.2034012e-02, 9.0576476e-01],
       [9.9360472e-01, 6.3952007e-03, 1.7713636e-07],
       [7.6590589e-04, 9.9923408e-01, 7.2199725e-11],
       [3.5946585e-05, 9.9996400e-01, 4.5454566e-15],
       [9.9330103e-01, 6.6987542e-03, 2.7103613e-07],
       [9.9330103e-01, 6.6987542e-03, 2.7103613e-07],
       [1.3456366e-02, 9.3486392e-01, 5.1679734e-02],
       [2.6049574e-07, 9.9999952e-01, 2.5642558e-07],
       [9.9330103e-01, 6.6987542e-03, 2.7103613e-07],
       [2.3932655e-04, 6.3594721e-02, 9.3616587e-01],
       [9.0159150e-04, 7.9444759e-02, 9.1965365e-01],
       [2.3272466e-02, 9.6709329e-01, 9.6341940e-03],
       [4.4117826e-01, 1.1305902e-01, 4.4576275e-01],
       [4.7228800e-04, 7.1312137e-02, 9.2821556e-01],
       [1.3568453e-04, 5.7757817e-02, 9.4210654e-01],
       [9.3622553e-01, 6.2640779e-02, 1.1336915e-03],
       [9.7528934e-01, 2.4710635e-02, 1.5274074e-08],
       [9.3313202e-04, 9.9906689e-01, 4.1811834e-08],
       [9.7528934e-01, 2.4710635e-02, 1.5274074e-08],
       [5.7261725e-05, 9.5395997e-02, 9.0454674e-01],
       [1.0568111e-02, 1.1802613e-01, 8.7140578e-01],
       [2.3272466e-02, 9.6709329e-01, 9.6341940e-03],
       [9.3275440e-01, 6.7237705e-02, 7.8778294e-06],
       [1.3568453e-04, 5.7757817e-02, 9.4210654e-01],
       [4.5447669e-05, 4.7909454e-02, 9.5204514e-01],
       [3.2433758e-03, 9.8010518e-02, 8.9874607e-01],
       [1.3568453e-04, 5.7757817e-02, 9.4210654e-01],
       [4.4117826e-01, 1.1305902e-01, 4.4576275e-01],
       [4.7228800e-04, 7.1312137e-02, 9.2821556e-01],
       [9.5335782e-01, 4.6641584e-02, 5.3061785e-07],
       [9.9330103e-01, 6.6987542e-03, 2.7103613e-07],
       [5.7261725e-05, 9.5395997e-02, 9.0454674e-01],
       [9.5335782e-01, 4.6641584e-02, 5.3061785e-07],
       [9.5335782e-01, 4.6641584e-02, 5.3061785e-07],
       [1.1357698e-04, 9.9936503e-01, 5.2144233e-04],
       [9.3275440e-01, 6.7237742e-02, 7.8778448e-06],
       [9.9438173e-01, 5.6183534e-03, 4.6722878e-08],
       [3.2433758e-03, 9.8010518e-02, 8.9874607e-01],
       [9.3313202e-04, 9.9906689e-01, 4.1811834e-08],
       [9.9438173e-01, 5.6183534e-03, 4.6722878e-08],
       [3.5946585e-05, 9.9996400e-01, 4.5454566e-15],
       [2.7193356e-01, 2.9226997e-01, 4.3579647e-01],
       [2.3272466e-02, 9.6709329e-01, 9.6341940e-03],
       [2.6049574e-07, 9.9999952e-01, 2.5642558e-07],
       [1.0023474e-02, 8.5710621e-01, 1.3287039e-01],
       [6.8381362e-02, 9.3160456e-01, 1.4093845e-05],
       [9.9438173e-01, 5.6183534e-03, 4.6722878e-08],
       [2.9017421e-04, 8.2932997e-01, 1.7037985e-01],
       [9.3622553e-01, 6.2640779e-02, 1.1336915e-03],
       [3.2433758e-03, 9.8010518e-02, 8.9874607e-01],
       [8.1580570e-03, 9.9174446e-01, 9.7512551e-05],
       [2.2011888e-03, 9.2034012e-02, 9.0576476e-01],
       [8.1580570e-03, 9.9174446e-01, 9.7512551e-05],
       [4.9097359e-02, 9.5090264e-01, 3.1048848e-09],
       [3.2992369e-07, 9.9999964e-01, 6.8688070e-22],
       [7.6590438e-04, 9.9923408e-01, 7.2199594e-11],
       [2.2011888e-03, 9.2034012e-02, 9.0576476e-01],
       [2.3272466e-02, 9.6709329e-01, 9.6341940e-03],
       [7.6590438e-04, 9.9923408e-01, 7.2199594e-11],
       [7.6590438e-04, 9.9923408e-01, 7.2199594e-11],
       [7.6590438e-04, 9.9923408e-01, 7.2199594e-11],
       [6.7786300e-01, 1.8743446e-01, 1.3470256e-01],
       [9.9234313e-01, 7.6562306e-03, 5.6153419e-07],
       [6.9263726e-01, 9.9440821e-02, 2.0792198e-01],
       [2.9017421e-04, 8.2932997e-01, 1.7037985e-01],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [6.9263721e-01, 9.9440813e-02, 2.0792198e-01],
       [9.9330103e-01, 6.6987542e-03, 2.7103613e-07],
       [7.0184833e-01, 8.8495493e-02, 2.0965612e-01],
       [2.7193356e-01, 2.9226997e-01, 4.3579647e-01],
       [7.6590438e-04, 9.9923408e-01, 7.2199594e-11],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [2.6388110e-05, 9.9514413e-01, 4.8295534e-03],
       [1.0568111e-02, 1.1802613e-01, 8.7140578e-01],
       [5.0756789e-06, 9.9972361e-01, 2.7130864e-04],
       [9.3275440e-01, 6.7237705e-02, 7.8778294e-06],
       [1.8825541e-04, 6.1061300e-02, 9.3875051e-01],
       [1.0846187e-01, 8.9123058e-01, 3.0757787e-04],
       [3.0326344e-02, 9.6145451e-01, 8.2191294e-03],
       [9.3313202e-04, 9.9906689e-01, 4.1811834e-08],
       [8.1580570e-03, 9.9174446e-01, 9.7512551e-05],
       [1.0846187e-01, 8.9123058e-01, 3.0757787e-04],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [2.7193356e-01, 2.9226997e-01, 4.3579647e-01],
       [3.0326344e-02, 9.6145451e-01, 8.2191294e-03],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [9.7528934e-01, 2.4710635e-02, 1.5274074e-08],
       [4.4117826e-01, 1.1305902e-01, 4.4576275e-01],
       [1.0568111e-02, 1.1802613e-01, 8.7140578e-01],
       [3.2433758e-03, 9.8010518e-02, 8.9874607e-01],
       [4.7612681e-05, 4.8293665e-02, 9.5165873e-01],
       [3.5946585e-05, 9.9996400e-01, 4.5454566e-15],
       [7.6590438e-04, 9.9923408e-01, 7.2199594e-11],
       [8.1580570e-03, 9.9174446e-01, 9.7512551e-05],
       [8.0922864e-06, 9.9243051e-01, 7.5614662e-03],
       [6.8381362e-02, 9.3160456e-01, 1.4093845e-05],
       [3.0326344e-02, 9.6145451e-01, 8.2191294e-03],
       [9.9438173e-01, 5.6183534e-03, 4.6722878e-08],
       [2.3272455e-02, 9.6709329e-01, 9.6341986e-03],
       [4.5447669e-05, 4.7909454e-02, 9.5204514e-01],
       [9.9330103e-01, 6.6987542e-03, 2.7103613e-07],
       [3.2433758e-03, 9.8010518e-02, 8.9874607e-01],
       [3.2992369e-07, 9.9999964e-01, 6.8688070e-22],
       [1.3456366e-02, 9.3486392e-01, 5.1679734e-02],
       [2.6049574e-07, 9.9999952e-01, 2.5642558e-07],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [9.3313202e-04, 9.9906689e-01, 4.1811834e-08],
       [4.9097359e-02, 9.5090264e-01, 3.1048848e-09],
       [9.3275440e-01, 6.7237705e-02, 7.8778294e-06],
       [4.9097359e-02, 9.5090264e-01, 3.1048848e-09],
       [7.6093784e-05, 5.2332379e-02, 9.4759154e-01],
       [8.1580570e-03, 9.9174446e-01, 9.7512551e-05],
       [5.2213854e-05, 4.9063981e-02, 9.5088375e-01],
       [3.5946585e-05, 9.9996400e-01, 4.5454566e-15],
       [7.6590438e-04, 9.9923408e-01, 7.2199594e-11],
       [9.7528934e-01, 2.4710635e-02, 1.5274074e-08],
       [1.3568453e-04, 5.7757817e-02, 9.4210654e-01],
       [2.6049574e-07, 9.9999952e-01, 2.5642558e-07],
       [9.9509108e-01, 4.9087466e-03, 5.9957081e-08],
       [8.1580570e-03, 9.9174446e-01, 9.7512551e-05],
       [9.9330103e-01, 6.6987542e-03, 2.7103613e-07],
       [2.2011888e-03, 9.2034012e-02, 9.0576476e-01],
       [9.7528934e-01, 2.4710635e-02, 1.5274074e-08],
       [4.5447669e-05, 4.7909454e-02, 9.5204514e-01],
       [1.5646046e-02, 1.2514652e-01, 8.5920745e-01],
       [4.5447669e-05, 4.7909454e-02, 9.5204514e-01],
       [7.0449010e-02, 1.5088785e-01, 7.7866316e-01],
       [9.9360472e-01, 6.3952007e-03, 1.7713636e-07],
       [5.0756789e-06, 9.9972361e-01, 2.7130864e-04],
       [6.5579246e-05, 5.1017802e-02, 9.4891661e-01],
       [3.2433772e-03, 9.8010562e-02, 8.9874607e-01],
       [1.0846181e-01, 8.9123058e-01, 3.0757757e-04],
       [1.1357708e-04, 9.9936503e-01, 5.2144285e-04],
       [4.9097359e-02, 9.5090264e-01, 3.1048848e-09],
       [9.5335782e-01, 4.6641584e-02, 5.3061785e-07],
       [5.4868535e-05, 4.9482934e-02, 9.5046228e-01],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [1.3568453e-04, 5.7757817e-02, 9.4210654e-01],
       [1.5646046e-02, 1.2514652e-01, 8.5920745e-01],
       [4.9097359e-02, 9.5090264e-01, 3.1048848e-09],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [4.4117826e-01, 1.1305902e-01, 4.4576275e-01],
       [4.7228800e-04, 7.1312137e-02, 9.2821556e-01],
       [6.9263726e-01, 9.9440821e-02, 2.0792198e-01],
       [9.9438173e-01, 5.6183534e-03, 4.6722878e-08],
       [7.0184833e-01, 8.8495493e-02, 2.0965612e-01],
       [9.7528934e-01, 2.4710635e-02, 1.5274074e-08],
       [1.0568111e-02, 1.1802613e-01, 8.7140578e-01],
       [1.3456366e-02, 9.3486392e-01, 5.1679734e-02],
       [1.9217348e-05, 4.1310169e-02, 9.5867068e-01],
       [7.6590438e-04, 9.9923408e-01, 7.2199594e-11],
       [1.0568111e-02, 1.1802613e-01, 8.7140578e-01],
       [1.5646046e-02, 1.2514652e-01, 8.5920745e-01],
       [7.6590438e-04, 9.9923408e-01, 7.2199594e-11],
       [1.8825541e-04, 6.1061300e-02, 9.3875051e-01],
       [2.3272466e-02, 9.6709329e-01, 9.6341940e-03],
       [9.9330103e-01, 6.6987542e-03, 2.7103613e-07],
       [9.9438173e-01, 5.6183534e-03, 4.6722878e-08],
       [2.7193356e-01, 2.9226997e-01, 4.3579647e-01],
       [5.2213854e-05, 4.9063981e-02, 9.5088375e-01],
       [1.8825541e-04, 6.1061300e-02, 9.3875051e-01],
       [3.4961957e-01, 3.1459177e-01, 3.3578873e-01],
       [4.5447669e-05, 4.7909454e-02, 9.5204514e-01],
       [5.7261786e-05, 9.5396020e-02, 9.0454674e-01],
       [3.2433758e-03, 9.8010518e-02, 8.9874607e-01],
       [8.5504991e-01, 6.9153644e-02, 7.5796537e-02],
       [3.8490526e-02, 1.4147425e-01, 8.2003516e-01],
       [9.5335782e-01, 4.6641584e-02, 5.3061785e-07],
       [8.0922864e-06, 9.9243051e-01, 7.5614662e-03],
       [3.5702065e-01, 6.2901068e-01, 1.3968632e-02],
       [2.3932655e-04, 6.3594721e-02, 9.3616587e-01],
       [3.0326344e-02, 9.6145451e-01, 8.2191294e-03],
       [3.2433758e-03, 9.8010518e-02, 8.9874607e-01],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [9.5335782e-01, 4.6641584e-02, 5.3061785e-07],
       [3.2992369e-07, 9.9999964e-01, 6.8688070e-22],
       [4.7612681e-05, 4.8293665e-02, 9.5165873e-01],
       [8.5504991e-01, 6.9153644e-02, 7.5796537e-02],
       [5.2213854e-05, 4.9063981e-02, 9.5088375e-01],
       [9.9330103e-01, 6.6987542e-03, 2.7103613e-07],
       [3.7700914e-02, 4.8230508e-01, 4.7999397e-01],
       [6.7786300e-01, 1.8743446e-01, 1.3470256e-01],
       [4.7228800e-04, 7.1312137e-02, 9.2821556e-01],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [7.6564920e-01, 2.3428036e-01, 7.0478025e-05],
       [1.5646046e-02, 1.2514652e-01, 8.5920745e-01],
       [1.5230008e-04, 9.9955934e-01, 2.8832073e-04],
       [3.2992369e-07, 9.9999964e-01, 6.8688070e-22],
       [8.0922864e-06, 9.9243051e-01, 7.5614662e-03],
       [9.9360472e-01, 6.3952007e-03, 1.7713636e-07],
       [3.2992369e-07, 9.9999964e-01, 6.8688070e-22],
       [3.5946585e-05, 9.9996400e-01, 4.5454566e-15],
       [1.3456366e-02, 9.3486392e-01, 5.1679734e-02],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [1.8825504e-04, 6.1061285e-02, 9.3875051e-01],
       [9.3622553e-01, 6.2640734e-02, 1.1336899e-03],
       [4.5447669e-05, 4.7909454e-02, 9.5204514e-01],
       [7.0449010e-02, 1.5088785e-01, 7.7866316e-01],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [1.1357708e-04, 9.9936503e-01, 5.2144285e-04],
       [4.4117826e-01, 1.1305902e-01, 4.4576275e-01],
       [3.5946585e-05, 9.9996400e-01, 4.5454566e-15],
       [9.9330103e-01, 6.6987542e-03, 2.7103613e-07],
       [4.4117826e-01, 1.1305902e-01, 4.4576275e-01],
       [4.5447669e-05, 4.7909454e-02, 9.5204514e-01],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [5.0756789e-06, 9.9972361e-01, 2.7130864e-04],
       [9.7528934e-01, 2.4710635e-02, 1.5274074e-08],
       [1.5230008e-04, 9.9955934e-01, 2.8832073e-04],
       [9.9360472e-01, 6.3952007e-03, 1.7713636e-07],
       [7.0184833e-01, 8.8495493e-02, 2.0965612e-01],
       [1.0568111e-02, 1.1802613e-01, 8.7140578e-01],
       [7.0449010e-02, 1.5088785e-01, 7.7866316e-01],
       [2.6049574e-07, 9.9999952e-01, 2.5642558e-07],
       [1.8825541e-04, 6.1061300e-02, 9.3875051e-01],
       [3.5946585e-05, 9.9996400e-01, 4.5454566e-15],
       [1.5538449e-03, 8.6928710e-02, 9.1151738e-01],
       [9.3313202e-04, 9.9906689e-01, 4.1811834e-08],
       [4.7228800e-04, 7.1312137e-02, 9.2821556e-01],
       [2.3272466e-02, 9.6709329e-01, 9.6341940e-03],
       [1.8825541e-04, 6.1061300e-02, 9.3875051e-01],
       [5.3669867e-04, 9.9822444e-01, 1.2388078e-03],
       [3.2433758e-03, 9.8010518e-02, 8.9874607e-01],
       [2.3932655e-04, 6.3594721e-02, 9.3616587e-01],
       [1.3456366e-02, 9.3486392e-01, 5.1679734e-02],
       [1.3568453e-04, 5.7757817e-02, 9.4210654e-01],
       [6.5579246e-05, 5.1017787e-02, 9.4891661e-01],
       [4.9097314e-02, 9.5090270e-01, 3.1048850e-09],
       [9.3275440e-01, 6.7237705e-02, 7.8778294e-06],
       [3.0326344e-02, 9.6145451e-01, 8.2191294e-03],
       [9.3275440e-01, 6.7237705e-02, 7.8778294e-06],
       [2.3932655e-04, 6.3594721e-02, 9.3616587e-01],
       [7.0184833e-01, 8.8495493e-02, 2.0965612e-01],
       [3.5946585e-05, 9.9996400e-01, 4.5454566e-15],
       [1.0568111e-02, 1.1802613e-01, 8.7140578e-01],
       [3.0326344e-02, 9.6145451e-01, 8.2191294e-03],
       [1.0023474e-02, 8.5710621e-01, 1.3287039e-01],
       [2.3272466e-02, 9.6709329e-01, 9.6341940e-03],
       [7.0184833e-01, 8.8495493e-02, 2.0965612e-01],
       [1.0568111e-02, 1.1802613e-01, 8.7140578e-01],
       [1.0023474e-02, 8.5710621e-01, 1.3287039e-01],
       [9.3622553e-01, 6.2640779e-02, 1.1336915e-03],
       [2.3272466e-02, 9.6709329e-01, 9.6341940e-03],
       [7.0184833e-01, 8.8495493e-02, 2.0965612e-01],
       [9.9360472e-01, 6.3952007e-03, 1.7713636e-07],
       [8.2500614e-03, 1.1801177e-01, 8.7373817e-01],
       [7.6590438e-04, 9.9923408e-01, 7.2199594e-11],
       [2.3932655e-04, 6.3594721e-02, 9.3616587e-01],
       [4.7228800e-04, 7.1312137e-02, 9.2821556e-01],
       [7.6564920e-01, 2.3428036e-01, 7.0478025e-05],
       [9.3313202e-04, 9.9906689e-01, 4.1811834e-08],
       [6.8381362e-02, 9.3160456e-01, 1.4093845e-05],
       [6.9263726e-01, 9.9440821e-02, 2.0792198e-01],
       [6.8381362e-02, 9.3160456e-01, 1.4093845e-05],
       [8.1580570e-03, 9.9174446e-01, 9.7512551e-05],
       [9.5335782e-01, 4.6641584e-02, 5.3061785e-07],
       [9.3313202e-04, 9.9906689e-01, 4.1811834e-08],
       [2.6049574e-07, 9.9999952e-01, 2.5642558e-07]], dtype=float32)

In [18]:
predicted_class = np.argmax(predictions, axis=1)

predicted_class

array([2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 1,
       2, 0, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 0, 0, 2, 2, 0,
       2, 0, 0, 0, 2, 1, 2, 2, 1, 2, 0, 0, 0, 2, 1, 1, 2, 0, 1, 1, 0, 0,
       1, 1, 0, 2, 2, 1, 2, 2, 2, 0, 0, 1, 0, 2, 2, 1, 0, 2, 2, 2, 2, 2,
       2, 0, 0, 2, 0, 0, 1, 0, 0, 2, 1, 0, 1, 2, 1, 1, 1, 1, 0, 1, 0, 2,
       1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 2, 1, 1,
       1, 2, 1, 0, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 0, 1, 2, 0, 2, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 2, 1, 1, 0,
       2, 1, 0, 1, 0, 2, 0, 2, 2, 2, 2, 0, 1, 2, 2, 1, 1, 1, 0, 2, 1, 2,
       2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 1, 2, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2,
       2, 0, 2, 2, 2, 0, 2, 0, 1, 1, 2, 1, 2, 1, 0, 1, 2, 0, 2, 0, 1, 0,
       2, 1, 0, 2, 1, 1, 1, 0, 1, 1, 1, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 2,
       2, 1, 1, 0, 1, 0, 0, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2,
       2, 1, 0, 1, 0, 2, 0, 1, 2, 1, 1, 1, 0, 2, 1, 0, 1, 0, 0, 2, 1, 2,
       2, 0, 1, 1, 0, 1, 1, 0, 1, 1])

In [19]:
model.save("milk_quality_ann.keras")